version: '3.8'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  app:
    image: movies-service:0.1
    environment:
      - DB_HOST=db
    ports:
      - '8080:8080'
    depends_on:
      - db
