apiVersion: v1
kind: Namespace
metadata:
  name: kuma-mesh
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-app
  namespace: kuma-mesh
spec:
  selector:
    matchLabels:
      app: movies-app
  replicas: 1
  template:
    metadata:
      labels:
        app: movies-app
    spec:
      containers:
        - name: movies-service
          image: "movies-service"
          env:
            - name: APP_VERSION
              value: "1.0"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: movies-app
  namespace: kuma-mesh
  annotations:
    8000.service.kuma.io/protocol: http
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: movies-app
  ports:
    - protocol: TCP
      port: 8080
