/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package greeting.service

import io.javalin.Javalin

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val app = Javalin.create().start(8080)
    app.get("/greet") { it.result("Hello World") }
}
